[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]
command = "tuigreet -t -c Hyprland -g '╔────────────────────╗\n│ welcome to my cave │\n╚────────────────────╝' --asterisks --asterisks-char ■ --theme 'border=gray;text=lightred;input=lightblue;button=red;action=gray;prompt=lightred;title=lightred'"


user = "greeter"


# `agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
# with whatever you want started, such as `sway`.
#command = "agreety --cmd /bin/sh"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
#user = "greeter"
